version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    image: backendp2g9
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    image: frontendp2g9
    ports:
      - '3000:3000'
    depends_on:
      - backend